{
  "name": "release",
  "on": {
    "push": {
      "tags": [
        "v*.*.*"
      ]
    }
  },
  "jobs": {
    "release": {
      "name": "Create GitHub Release",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Setup | Checkout",
          "uses": "actions/checkout@v2.3.4",
          "with": {
            "fetch-depth": 0
          }
        },
        {
          "name": "Setup | Archive Module",
          "run": "7z a ps-mpd.zip MPD"
        },
        {
          "name": "Release | Release",
          "env": {
            "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
          },
          "run": "gh release create ${{ github.ref_name }} ps-mpd.zip --generate-notes --title ${{ github.ref_name }} "
        }
      ]
    }
  }
}