{
  "name": "Release",
  "on": {
    "push": {
      "tags": [
        "v*.*.*"
      ]
    }
  },
  "jobs": {
    "release": {
      "name": "Build Release Binaries",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "checkout",
          "uses": "actions/checkout@v4",
          "with": {
            "fetch-depth": 0
          }
        },
        {
          "name": "build",
          "run": "pwsh -nologo -noprofile ./build.ps1"
        },
        {
          "name": "archive module",
          "run": "cd bin/MPD && 7z a ../../MPD.7z . && cd -"
        },
        {
          "name": "create github release",
          "env": {
            "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
          },
          "run": "gh release create ${{ github.ref_name }} MPD.7z --generate-notes --title ${{ github.ref_name }}"
        }
      ]
    }
  }
}
